### PR TITLE
Visual Upgrades for the Blog

### PR DESCRIPTION
**Pull request by jagtalon**
## Font Changes

We're now using Proxima Nova for headers and Athelas for the content.

screen shot 2019-01-04 at 11 51 08 am

screen shot 2019-01-04 at 11 51 06 am

## Blue Branding Color

We're now using these colors for branding:

```css
    --cornflower-blue: #678fff;
    --cornflower-blue-dark: #3F66D5;
```

screen shot 2019-01-04 at 11 53 03 am

screen shot 2019-01-04 at 11 53 31 am

## Add support for full-width images

We can now set full-width images in the blog.

screen shot 2019-01-04 at 11 54 40 am

## How to test:

1. Make sure you have ghost v1. Install using `ghost install local --v1`
2. Delete the image directory at `content/images` by running `rm -r content/images`
2. Use https://cl.ly/c6aeacf41a98/download/images.zip and extract to `content/images` by running `zip images.zip`
3. Delete all the content in your Ghost instance.

screen shot 2019-01-04 at 11 57 40 am

4. Replace it with https://cl.ly/78fb044067e2/download/duckduckgo-blog.ghost.2019-01-04.json
5. You should now have parity with https://spreadprivacy.com/. 
6. See if there are any broken blog posts.

### CODE REVIEW

**Comment by tagawa** [comment]
Thanks for the ping @jagtalon. Looking good and I like the Athelas font for content.
As mentioned separately, I have an [issue with the contrast for --cornflower-blue and white text](https://snook.ca/technical/colour_contrast/colour.html#fg=FFFFFF,bg=678fff), but --cornflower-blue-dark seems good so that could be an alternative to try.

**Comment by moollaza** [comment]
@jagtalon Thanks! This LGTM :+1:

**Comment by moollaza** [comment]
@jagtalon just noticed we have /built and /buil**d** -- are they both necessary?

**Comment by jagtalon** [comment]
@moollaza ah sweet let me see what the actual difference is. I know `built/` is necessary but I don't know about build. 

Also with regards to the color, I'll revert the changes I made in https://github.com/duckduckgo/Casper/pull/20/commits/d51c3e1c49de1d61887987b6c7fe2d2720ccad55 and https://github.com/duckduckgo/Casper/pull/20/commits/7a598dc726aebfc7d84e9bc92b210164c9872d58 based on @tagawa's comments.

**Comment by jagtalon** [comment]
Reverted to old colors

screen shot 2019-01-07 at 2 46 52 pm

**Comment by moollaza** [comment]
@jagtalon Thanks! This LGTM :+1:

**Comment by jagtalon** [comment]
Thank you!

**Pull request merged**
